"""initial schema

Revision ID: 54b3e2f554e6
Revises: 
Create Date: 2025-12-05 12:05:57.555648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b3e2f554e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attendances_user_date', table_name='attendances')
    op.drop_index('idx_attendances_user_id', table_name='attendances')
    op.create_index(op.f('ix_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.drop_column('attendances', 'version')
    op.drop_index('idx_leave_applications_status', table_name='leave_applications')
    op.drop_index('idx_leave_applications_user_id', table_name='leave_applications')
    op.drop_index('idx_leave_applications_user_status', table_name='leave_applications')
    op.create_index(op.f('ix_leave_applications_status'), 'leave_applications', ['status'], unique=False)
    op.create_index(op.f('ix_leave_applications_user_id'), 'leave_applications', ['user_id'], unique=False)
    op.drop_index('idx_overtime_applications_status', table_name='overtime_applications')
    op.drop_index('idx_overtime_applications_user_id', table_name='overtime_applications')
    op.drop_index('idx_overtime_applications_user_status', table_name='overtime_applications')
    op.create_index(op.f('ix_overtime_applications_status'), 'overtime_applications', ['status'], unique=False)
    op.create_index(op.f('ix_overtime_applications_user_id'), 'overtime_applications', ['user_id'], unique=False)
    op.drop_index('idx_users_department_id', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_wechat_openid', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_wechat_openid', 'users', ['wechat_openid'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_department_id', 'users', ['department_id'], unique=False)
    op.drop_index(op.f('ix_overtime_applications_user_id'), table_name='overtime_applications')
    op.drop_index(op.f('ix_overtime_applications_status'), table_name='overtime_applications')
    op.create_index('idx_overtime_applications_user_status', 'overtime_applications', ['user_id', 'status'], unique=False)
    op.create_index('idx_overtime_applications_user_id', 'overtime_applications', ['user_id'], unique=False)
    op.create_index('idx_overtime_applications_status', 'overtime_applications', ['status'], unique=False)
    op.drop_index(op.f('ix_leave_applications_user_id'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_status'), table_name='leave_applications')
    op.create_index('idx_leave_applications_user_status', 'leave_applications', ['user_id', 'status'], unique=False)
    op.create_index('idx_leave_applications_user_id', 'leave_applications', ['user_id'], unique=False)
    op.create_index('idx_leave_applications_status', 'leave_applications', ['status'], unique=False)
    op.add_column('attendances', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
    op.drop_index(op.f('ix_attendances_user_id'), table_name='attendances')
    op.create_index('idx_attendances_user_id', 'attendances', ['user_id'], unique=False)
    op.create_index('idx_attendances_user_date', 'attendances', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###
